### ISSUE TITLE
프로필 소개 변경 이슈

### ISSUE THREAD

**Issue by samweol** [FRONTENDSCHOOL7/final-11-10Duck#53]
- 사진 변경안하고 소개만 변경하는 경우 이미지파일이 깨진상태 (소개뿐만 아니라 이미지를 변경하지 않는 모든 경우)
![스크린샷 2023-10-28 오후 5 52 35](https://github.com/FRONTENDSCHOOL7/final-11-10Duck/assets/94788360/a0235efd-2b84-4581-8d4d-d6de272131c4)
![스크린샷 2023-10-28 오후 5 52 44](https://github.com/FRONTENDSCHOOL7/final-11-10Duck/assets/94788360/3502bf40-4e0b-41ae-8d5f-5eaa328c7f2f)
- 이미지만 변경한 이후에는 다시 이미지가 잘뜸.

**Comment by oqoqoh** [comment]
수정 완료
