### ISSUE TITLE
Layout 컴포넌트 코드리뷰 피드백

### ISSUE THREAD

**Issue by samweol** [FRONTENDSCHOOL7/final-11-10Duck#7]
- 바텀 탭 라인 색상 767676이 아닌 DBDBDB. 피그마 확인 바람
- 레이아웃 전체 사이즈가 피그마엔 390 * 844 로 나와있는데 실제 레이아웃 크기와 다름
- 배경과 구분을 위해 추가된 border은 나중에 제거 바람
- Layout Header, Footer말고 ContentContainer 얘기 했었는데 왜 없어진걸까요 .. ? 머리 꼬리로 구분하기 시작한거면 머리 몸 꼬리로 구분하는게 더좋은 컴포넌트 구조라고 판단됩니다!
- Header (피드기준) 사이즈가 390 * 48 인데 다릅니다 확인부탁드려요!

**Comment by samweol** [comment]
layout 양옆에 16px이라는 간격이 있어요! content 컴포넌트 안에서 padding이나 margin값을 넣어준다면, 일일이 16px을 안넣어도 되니 좋겠지요 ?

**Comment by samweol** [comment]
규영님... 레이아웃 전체 배치를 flex로 해두셨네요? .. 근데 이러면 나중에 content 영역안에 애들이 들어가면 원하는 대로배치가안되어서 .. flex로 두면 안될 것 같아요 .. height가 고정이니까.. position으로 바텀탭을 맞추는게 맞았을 것 같은데ㅛ ? ㅜ

**Comment by oqoqoh** [comment]
> 규영님... 레이아웃 전체 배치를 flex로 해두셨네요? .. 근데 이러면 나중에 content 영역안에 애들이 들어가면 원하는 대로배치가안되어서 .. flex로 두면 안될 것 같아요 .. height가 고정이니까.. position으로 바텀탭을 맞추는게 맞았을 것 같은데ㅛ ? ㅜ

* 규영님... 레이아웃 전체 배치를 flex로 해두셨네요?...  
    * 이 부분 17시쯤에 유진 멘토님한테 조언을 들었는데요. header, footer 탭을 포지션으로 맞추는것보다 가장 상단에 layout만 flex로 하고 content 부분은 기본 스타일 없이 glow만 적용해 쓰는 방법 추천받았습니다. 그래서 이 방법으로 수정 중입니다.
*   layout 양옆에 16px이라는 간격이 있어요!... 
    * 넵 확인할께요
*   레이아웃 전체 사이즈가 피그마엔 390 * 844 로 나와있는데 실제 레이아웃 크기와 다름
    * 피그마에 모바일 상단(전파표시 및 시간 부분) 제외하고 height가 826, 844 등 조금씩 다른데 820인 레이아웃이 더 많아서, 820으로 적용할께요!

**Comment by samweol** [comment]
규영님!  Layout에 추가되었으면 하는 부분이 있어서 코멘트 남겨요!
- layoutContent에 position:relative 스타일링 추가하기 이 친구를 기준으로 위치 잡는 경우가 있어서 추가만 부탁드려요! 스타일의 변화는 없을거예요!
- layoutContent에서 overflow의 경우 scroll 생기게 변경 부탁드립니다!
