### ISSUE TITLE
아이콘 색상 변경

### ISSUE THREAD

**Issue by samweol** [FRONTENDSCHOOL7/final-11-10Duck#82]
![스크린샷 2023-11-01 오전 11 41 27](https://github.com/FRONTENDSCHOOL7/final-11-10Duck/assets/94788360/eb25870d-15a7-4450-af0a-8d24443fe6db)
- 돋보기 아이콘 (assets/icon/icon-search.png)
![스크린샷 2023-11-01 오전 11 41 34](https://github.com/FRONTENDSCHOOL7/final-11-10Duck/assets/94788360/61f37e33-3bda-4689-8cad-ffeb6b5fdc72)
- 이미지 추가 버튼 아이콘 (assets/upload-file.png)
![스크린샷 2023-11-01 오전 11 41 55](https://github.com/FRONTENDSCHOOL7/final-11-10Duck/assets/94788360/6499f826-0a24-4bd2-8aef-8fb424b8d485)
- 뒤로가기, 더보기 버튼 (assets/icon/icon-arrow-left.png, assets/icon/icon-more-vertical.png)
파일명 똑같이 만들어서 덮어쓰기로 부탁드립니당

**Comment by samweol** [comment]
![스크린샷 2023-11-01 오후 1 24 42](https://github.com/FRONTENDSCHOOL7/final-11-10Duck/assets/94788360/b1e8bab0-3196-4893-98f7-21e350b4c83e)
- 좋아요 버튼(assets/icon/icon-heart-active.png)

**Comment by oqoqoh** [comment]
수정완료
